### ISSUE TITLE
Modify clang driver to select Repo as the default target.

### ISSUE THREAD

**Issue by MaggieYingYi** [SNSystems/llvm-project-prepo#156]
The task involves:

1.	Change the default target to Repo.
2.	Select rld as the default linker for Repo target.
3.	Use the musl-prepo library as the default C library.
4.	Use LLVM libc++ library (built using the musl-prepo) as the default C++ library.

**Comment by paulhuggett** [comment]
> Change the default target to Repo.

This is done by passing `LLVM_DEFAULT_TARGET_TRIPLE=x86_64-pc-linux-gnu-repo` when running cmake.

**Comment by paulhuggett** [comment]
As per my comment above, there's nothing to do here.
