### ISSUE TITLE
Crash while compiling OpenMP test case

### ISSUE THREAD

**Issue by CarlosAlbertoEnciso** [SNSystems/llvm-project-prepo#23]
Given the test case:

//--------------------------------------------
template <class T>
void update() {
  int a = 0;
  #pragma omp atomic update
  //#pragma omp atomic
  a += 3;
}

void update() {
  update<int>();
}
//--------------------------------------------

The following command line:
clang -cc1 -fopenmp -ast-print

causes the compiler to crash with the error message:

template <class T> void update() {
    int a = 0;
    #pragma omp atomic update
    a += 3;
}
template<> void update<int>() {
    int a = 0;
    #pragma omp atomic Unknown clause kind!
UNREACHABLE executed at /home/carlos/projects/llvm-prepo/sources/clang/include/clang/AST/OpenMPClause.h:5327!
Stack dump:
0.	Program arguments: bin/clang -cc1 -fopenmp -ast-print invalid_kind.cpp 
1.	<eof> parser at end of file
#0 0x0000000001a6ffd4 PrintStackTraceSignalHandler(void*) (bin/clang+0x1a6ffd4)
Aborted (core dumped)

**Comment by CarlosAlbertoEnciso** [comment]
The assertion occurs in the front-end

'TreeTransform.h'
template<typename Derived>
OMPClause *TreeTransform<Derived>::TransformOMPClause(OMPClause *S) {
}

It does not need any database. Just compile the given test case.

**Comment by CarlosAlbertoEnciso** [comment]
Further analysis to understand the issue:

1) Compile 'clang/lib/Sema/SemaTemplateInstantiate.cpp' with the options:

>bin/clang++ --target=x86_64-pc-linux-gnu-repo  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/lib/Sema -I/home/carlos/projects/llvm-prepo/sources/clang/lib/Sema -I/home/carlos/projects/llvm-prepo/sources/clang/include -Itools/clang/include -I/usr/include/libxml2 -Iinclude -I/home/carlos/projects/llvm-prepo/sources/llvm/include   -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -Wno-nested-anon-types  -O2 -fno-exceptions -fno-rtti    -fno-exceptions -fno-rtti -o ./SemaTemplateInstantiate.cpp.o -c /home/carlos/projects/llvm-prepo/sources/clang/lib/Sema/SemaTemplateInstantiate.cpp

2) Get hash for CU

>bin/repo-ticket-dump ./SemaTemplateInstantiate.cpp.o
df426db9c55829dc9b8947b6506fecfe

3) Dump CU

>bin/pstore-dump -compilation=df426db9c55829dc9b8947b6506fecfe clang.db > cu_all.log

4) From the log file:

The following names have the same hash: 2e195bb3083ea86de7e4a7ed06eae6c8

_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE24TransformOMPNowaitClauseEPNS_15OMPNowaitClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE24TransformOMPUntiedClauseEPNS_15OMPUntiedClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE27TransformOMPMergeableClauseEPNS_18OMPMergeableClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE22TransformOMPReadClauseEPNS_13OMPReadClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE23TransformOMPWriteClauseEPNS_14OMPWriteClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE24TransformOMPUpdateClauseEPNS_15OMPUpdateClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE25TransformOMPCaptureClauseEPNS_16OMPCaptureClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE24TransformOMPSeqCstClauseEPNS_15OMPSeqCstClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE25TransformOMPThreadsClauseEPNS_16OMPThreadsClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE22TransformOMPSIMDClauseEPNS_13OMPSIMDClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE25TransformOMPNogroupClauseEPNS_16OMPNogroupClauseE
_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE28TransformOMPDefaultmapClauseEPNS_19OMPDefaultmapClauseE

**Comment by CarlosAlbertoEnciso** [comment]
Taking just 2 cases:

_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE22TransformOMPReadClauseEPNS_13OMPReadClauseE

_ZN5clang13TreeTransformIN12_GLOBAL__N_120TemplateInstantiatorEE23TransformOMPWriteClauseEPNS_14OMPWriteClauseE

Mangled names for:

template <typename Derived>
OMPClause *TreeTransform<Derived>::TransformOMPReadClause(OMPReadClause *C) {
   ...
}

template <typename Derived>
OMPClause *TreeTransform<Derived>::TransformOMPWriteClause(OMPWriteClause *C) {
   ...
}

OMPReadClause and OMPWriteClause are derived from OMPClause; they have the same constructors signature:

  OMPReadClause(SourceLocation StartLoc, SourceLocation EndLoc)
      : OMPClause(OMPC_read, StartLoc, EndLoc) {}

  OMPWriteClause(SourceLocation StartLoc, SourceLocation EndLoc)
      : OMPClause(OMPC_write, StartLoc, EndLoc) {}

But they call their base class constructor with a specific enum value, which is not used by the hash calculation. Instead it uses the 'OpenMPClauseKind K'.

**Comment by CarlosAlbertoEnciso** [comment]
This is spin-off from the issue #7.

**Comment by MaggieYingYi** [comment]
To reproduce the issue, use the test.cpp:

```
$ less test.cpp

enum BaseKind { read, write };

class Base {
  BaseKind Kind;
protected:
  Base(BaseKind K) : Kind(K) {}
public:
  BaseKind getBaseKind() const { return Kind; }
  static bool classof(const Base *) { return true; }
};

class Read : public Base {
public:
  Read() : Base(read) {}
  static bool classof(const Base *T) { return T->getBaseKind() == read; }
};

class Write : public Base {
public:
  Write() : Base(write) {}
  static bool classof(const Base *T) { return T->getBaseKind() == write; }
};

Read GlobalRead;
Write GlobalWrite;
```

Compile the test.cpp:
```
$ clang -S -emit-llvm  --target=x86_64-pc-linux-gnu-repo test.cpp -o test.ll
$ less test.ll
...
!0 = !TicketNode(name: "GlobalRead", digest: [16 x i8] c"\AB\C2\FA|ReE\D7\84D\82\94F\CF\0C(", linkage: external, pruned: false)
!1 = !TicketNode(name: "GlobalWrite", digest: [16 x i8] c"\AB\C2\FA|ReE\D7\84D\82\94F\CF\0C(", linkage: external, pruned: true)
```
The variables of 'GlobalRead' and 'GlobalWrite' have the same digest, which is wrong. Because these two variables have the different type, they should have the different hash value.
