### ISSUE TITLE
Improve the repo metadata generation implementation (the “generateTicketMDs” function)

### ISSUE THREAD

**Issue by MaggieYingYi** [SNSystems/llvm-project-prepo#34]
This is spin-off from the issue https://github.com/SNSystems/llvm-project-prepo/issues/25, https://github.com/SNSystems/llvm-project-prepo/pull/31#discussion_r300584045.

Currently, the function of “generateTicketMDs” involved three significant loops:
1.  Go through the global objects building GOIMap and GVIMap, building a hash and setting the MD digest field.
2.  Iterate over GVIMap, computing a hash and set the MD digest field for GVs.
3.  Go through the global objects again, computing/updating its hash and setting the MD digest field if its dependents are in the GVIMap.

The task involved to find a more optimal implementation.

**Comment by MaggieYingYi** [comment]
The first improvement has been committed into the master branch 617f807.

**Comment by MaggieYingYi** [comment]
The `generateTicketMDs` implementation involved the two steps after commit 617f807.

Step 1: Calculate the GO's initial digest, contributions and dependencies.
Step 2: Accumulate the GO's digest using its contributions and dependencies and setting the GO's ticket metadata.

The `RepoMetadataGenerationPass` execution time (user time) of the SemaDeclAttr.cpp file is 20.321 seconds. Time is average of 4 iterations and based on the llvm-project-prepo master branch (30d6983306fe3).

**Comment by MaggieYingYi** [comment]
Currently, we use the recursive algorithm to calculate the GO’s digest.

Consider the following example:
```
int shared() {
  return 1;
}
int bar() {
  return shared();
}
int foo() {
  return shared();
}
int baz () {
  return shared();
}
```
In the Step 2, the hash calculation order is shown below.
```
| Order | Functions | Dependencies | Contributions |Calculated Functions | Functions with Metadata |
|-------|-----------|--------------|---------------|---------------------|-------------------------|
|   1   |  shared   |    ----      |    -----      | shared              | shared                  |
|   2   |   bar     | shared       |    -----      | shared, bar         | shared, bar             |
|   3   |   foo     | shared       |    -----      | shared, foo         | shared, bar, foo        |             
|   4   |   baz     | shared       |    -----      | shared, baz         | shared, bar, foo, baz   |    
                      
```
We could see that the `shared` function has been calculated four times, which is unnecessary.  After calculating the `shared` digest, the digest value has been saved into the ticket metadata of the `shared` function. When calculating other functions (`bar`, `foo`, and `baz`), the `shared` digest value could be gotten from the ticket metadata instead of recalculating it digest again.

We could see that the user time has been reduced from 20.321s to 6.98s (66% improvement).

**Comment by paulhuggett** [comment]
FWIW I've posted a [small program](https://github.com/paulhuggett/digraph-hash) to demonstrate a possible technique which caches the digests of each GO as it is visited (where possible). Hopefully, something like it can offer the performance benefits describes above but without the pitfalls of loop handling and input ordering that. Let me know what you think of it.

Note that the performance of the algorithm is dependent on the number of cyclic paths through the graph: these cannot be cached. My intuition is that these are (relatively) rare in out inputs, but it would nice to prove that.

**Comment by MaggieYingYi** [comment]
> 
> 
> Let me know what you think of it.
> 
Many thanks for working on this. I have read the algorithm and its implementation. The algorithm is brilliant and it will give the performance benefits by avoiding the recalculating the GO's digest. Since you are busying on the repo linker implementation, I will port the algorithm into the RepoMetadataGeneration pass.

>
> My intuition is that these are (relatively) rare in out inputs, but it would nice to prove that.
>
Once the algorithm is ported into the RepoMetadataGeneration pass, I will use upstream LLVM+Clang project to prove this.

**Comment by MaggieYingYi** [comment]
The cached hash algorithm passed the code review #86 and committed into the master branch 000ebc28f.
