### ISSUE TITLE
Duplicate entries for the dependent GOs in a compilation file.

### ISSUE THREAD

**Issue by MaggieYingYi** [SNSystems/llvm-project-prepo#45]
After applying the patch proposed in the pull request #43, the issue #41 has been fixed and the LLVM test results for the second time build are shown below.

```
Failing Tests (4):
    LLVM-Unit :: ExecutionEngine/Orc/./OrcJITTests/DummyRPC.ReturnErrorFailure
    LLVM-Unit :: ExecutionEngine/Orc/./OrcJITTests/DummyRPC.ReturnErrorSuccess
    LLVM-Unit :: ExecutionEngine/Orc/./OrcJITTests/DummyRPC.ReturnExpectedFailure
    LLVM-Unit :: ExecutionEngine/Orc/./OrcJITTests/DummyRPC.ReturnExpectedSuccess

  Expected Passes       : 30857
  Expected Failures     : 71
  Unsupported Tests   : 12291
  Unexpected Failures : 4
```
These four failed unit tests are written in the `llvm/unittests/ExecutionEngine/Orc/RPCUtilsTest.cpp` file.

**Comment by MaggieYingYi** [comment]
### **The detailed issue descriptions:**

These four failed unit tests are written in the `llvm/unittests/ExecutionEngine/Orc/RPCUtilsTest.cpp` file. If the `RPCUtilsTest.cpp` file is compiled twice, then dump the compilation record for `RPCUtilsTest.o`:
```
---
- file         : 
  compilations : 

                - digest  : 6c92e11c3fef855521f5e2991d226e80
                  fext    : { addr: 1781744, size: 984 }
                  name    : _ZZN28DummyRPC_TestCustomType_Test8TestBodyEvENK4$_14clEN4llvm8ExpectedI6RPCFooEE
                  linkage : internal
                - digest  : f32caa8f125ac1d362af64e554cd6d29
                  fext    : { addr: 1780680, size: 984 }
                  name    : _ZZN35DummyRPC_TestWithAltCustomType_Test8TestBodyEvENK4$_16clEN4llvm8ExpectedI6RPCBarEE
                  linkage : internal
                - digest  : 6c92e11c3fef855521f5e2991d226e80
                  fext    : { addr: 1781744, size: 984 }
                  name    : _ZZN28DummyRPC_TestCustomType_Test8TestBodyEvENK4$_14clEN4llvm8ExpectedI6RPCFooEE
                  linkage : internal
                - digest  : f32caa8f125ac1d362af64e554cd6d29
                  fext    : { addr: 1780680, size: 984 }
                  name    : _ZZN35DummyRPC_TestWithAltCustomType_Test8TestBodyEvENK4$_16clEN4llvm8ExpectedI6RPCBarEE
                  linkage : internal
---
```

You’ll find the fragments of `_ZZN35DummyRPC_TestWithAltCustomType_Test8TestBodyEvENK4$_16clEN4llvm8ExpectedI6RPCBarEE` and ` _ZZN28DummyRPC_TestCustomType_Test8TestBodyEvENK4$_14clEN4llvm8ExpectedI6RPCFooEE` have two entries in the compilation file.

**Comment by paulhuggett** [comment]
Could this be related to issue #40?

**Comment by MaggieYingYi** [comment]
> 
> 
> Could this be related to issue #40?

No, it is the different issue. I will explain the issue using a small IR code.

**Comment by MaggieYingYi** [comment]
I can’t reproduce the issue using a small C/C++ source code. To reproduce the issue, consider the following repo.ll code, which is generated after the first-time build:

```
target triple = "x86_64-pc-linux-gnu-repo"

define i32 @A() !repo_ticket !0 {
entry:
  %call = call i32 @B()
  ret i32 %call
}

define internal i32 @B() {
entry:
  ret i32 1
}


!repo.tickets = !{!0}

!0 = !TicketNode(name: "A", digest: [16 x i8] c"\0F\83D\96vz\F5\C9\00\02\EDe~[g\FA", linkage: external, pruned: false)
```
You could find the function `B` doesn’t have a TicketNode. The following steps explained the reason.


1. After `RepoMetadataGenerationPass`, the digests for `A` and `B` are generated.
2. After `RepoPruningPass`, there is **NO** pruning happen since there is **NO** database.
3. After `argpromotion` pass, the function `B` is reconstructed and its TicketNode metadata is lost. 
4. LLVM backend will create the TicketNode metadata for the Function `B`. The function `A` has an external fix-up to the function `B` and the TicketNode metadata of `B` is generated by the LLVM backend, therefore function `B` is saved into the dependent list of function `A`.
5. During repo object writer, both `A ` and `B` are written into the database.

```
$ rm -f clang.db
$ llc -filetype=obj repo.ll -o repo.v1.o
$ pstore-dump -all-compilations clang.db

---
      - digest      : 2d625aa24b8b70346b7bd4053b69d05d
        compilation :
                - digest  : 664bf1dd1dfb50f74909b8862f9bb0bc
                  fext    : { addr: 352, size: 104 }
                  name    : A
                  linkage : external
                - digest  : 1a907d11b14d9f2a556c4bd21d0f2334
                  fext    : { addr: 272, size: 46 }
                  name    : B
                  linkage : internal

...

$ pstore-dump –fragment=664bf1dd1dfb50f74909b8862f9bb0bc clang.db

      - digest   : 664bf1dd1dfb50f74909b8862f9bb0bc
        fragment :
            - type     : text
              contents :
                  align   : 16
                  data    :
                      - 0:      pushq   %rax
                      - 1:      callq   0
                      - 6:      popq    %rcx
                      - 7:      retq
                  ifixups : [ ]
                  xfixups :
                      - name   : B
                        type   : 4
                        offset : 2
                        addend : 18446744073709551612
            - type     : dependent
              contents :
                  - digest  : 1a907d11b14d9f2a556c4bd21d0f2334
                    fext    : { addr: 272, size: 46 }
                    name    : B
                    linkage : internal

```

If we build the code again (with the existing database), the following steps are involved.


1. After `RepoMetadataGenerationPass`, the digests for `A` and `B` are generated.
```
…
!repo.tickets = !{!0, !1}
!0 = !TicketNode(name: "A", digest: [16 x i8] c"\BC\B0\9B/\86\B8\09I\F7P\FB\1D\DD\F1Kf", linkage: external, pruned: false)
!1 = !TicketNode(name: "B", digest: [16 x i8] c"q)Tf\00H\C1\8C\B7e\E8U\CF\19'y", linkage: internal, pruned: false)
```

2. After `RepoPruningPass`, the function `A` is pruned and `A` and its dependent `B` have been added into the repo.tickets and their pruned flags are true. Since the function `B` digest saved in the database is calculated by the backend and after all the optimisation passes, which is different from the digest generated by the repo digest generation pass. Therefore, the function `B` is not pruned. The generated repo.tickets is shown below after `RepoPruningPass`.

```
!repo.tickets = !{!0, !1, !2}

!0 = !TicketNode(name: "A", digest: [16 x i8] c"\BC\B0\9B/\86\B8\09I\F7P\FB\1D\DD\F1Kf", linkage: external, pruned: true)
!1 = !TicketNode(name: "B", digest: [16 x i8] c"q)Tf\00H\C1\8C\B7e\E8U\CF\19'y", linkage: internal, pruned: false)
!2 = !TicketNode(name: "B", digest: [16 x i8] c"4#\0F\1D\D2KlU*\9FM\B1\11}\90\1A", linkage: internal, pruned: true)
```


3. After `argpromotion`, the function `B` is the same as the first-time build and it doesn’t have a TicketNode.
4. LLVM backend will create the TicketNode metadata for the Function B. 
5. During repo object writer, both `A ` and `B` are pruned and written as the compilation members. The function `B` is also in the fragments and is written into the compilation again. Therefore, there are two function `B` in the compilation file.

**Comment by MaggieYingYi** [comment]
The fix is put into the pull request https://github.com/SNSystems/llvm-project-prepo/pull/46 for the code review.

**Comment by MaggieYingYi** [comment]
The fix has been committed into the master branch (e9e4b9b ).
