### ISSUE TITLE
llvm-prepo: Incorrect representation of constant pool indices (CPI)

### ISSUE THREAD

**Issue by MaggieYingYi** [SNSystems/llvm-project-prepo#5]
This bug is spinning out from Bug 32.

When running the agg_pattern_fill.out, it gives the segmentation fault.
```
{{ CFLAGS         : "-O0" }}

AntiGrain Demo: AGG Example: Pattern Filling

{{begin}}
Segmentation fault (core dumped)
```

**Comment by paulhuggett** [comment]
> This bug is spinning out from Bug 32.
> When running the agg_pattern_fill.out, it gives the segmentation fault.

Is this still a bug? I don't know what "bug 32" refers to: ([issue 32](https://github.com/SNSystems/llvm-project-prepo/pull/32) doesn’t seem to be at all related). Unfortunately, no code is attached so I also don’t know how to set about reproducing the failure.

**Comment by paulhuggett** [comment]
No update, so closing.
