### ISSUE TITLE
Linking prints out b''b''b''b''b''b''b''b''b'' with python 3

### ISSUE THREAD

**Issue by rgal** [SNSystems/llvm-project-prepo#93]
When trying to build LLVM with the program repo (e.g. https://github.com/SNSystems/llvm-project-prepo/wiki/Build-LLVM-with-the-Repo-Compiler) using python 3, linking and archiving prints out b'' repeatedly. I think that this would happen linking anything with the link wrappers (e.g. hello world).

I think this is likely a problem in the link.py wrapper script (or related scripts).

Tested at revision 0768536cb689b68033ff1841fcff7c519f8641be, on Linux (Ubuntu 18.04), with python 3.

**Comment by paulhuggett** [comment]
Could use a little more information here, really… How to reproduce?

**Comment by rgal** [comment]
Sorry, that was a little vague. Added detail.

**Comment by paulhuggett** [comment]
Could this be closed now?
