### ISSUE TITLE
Build failures due to the `getSectionForConstant` function API change.

### ISSUE THREAD

**Issue by MaggieYingYi** [SNSystems/llvm-project-prepo#99]
Build the llvm-project-prepo (commit: 000ebc28) and pstore (commit: [13eacb6b](https://github.com/SNSystems/pstore/commit/13eacb6b12fc3d42313015f7ec03d57d0c0d7da6)) using the following command.

```
cmake.exe -G "Visual Studio 15 2017 Win64" -T host=x64 -DLLVM_ENABLE_PROJECTS="clang;pstore;rld;lld" -DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD=OFF ../llvm

```

Build failed with the following errors.

```
99>  RISCVTargetObjectFile.cpp
99>  e:\github\llvm-project-prepo\llvm\lib\target\riscv\RISCVTargetObjectFile.h(37): error C3668: 'llvm::RISCVELFTargetObjectFile::getSectionForConstant': method with override specifier 'override' did not override any base class methods
99>  E:\github\llvm-project-prepo\llvm\lib\Target\RISCV\RISCVTargetObjectFile.cpp(113): error C2660: 'llvm::TargetLoweringObjectFileELF::getSectionForConstant': function does not take 4 arguments
99>  E:\github\llvm-project-prepo\llvm\include\llvm/CodeGen/TargetLoweringObjectFileImpl.h(55): note: see declaration of 'llvm::TargetLoweringObjectFileELF::getSectionForConstant'
99>  RISCVTargetMachine.cpp
99>  e:\github\llvm-project-prepo\llvm\lib\target\riscv\RISCVTargetObjectFile.h(37): error C3668: 'llvm::RISCVELFTargetObjectFile::getSectionForConstant': method with override specifier 'override' did not override any base class methods
99>Done building target "ClCompile" in project "LLVMRISCVCodeGen.vcxproj" -- FAILED.
```

**Comment by paulhuggett** [comment]
It would be useful to know why this build fails but the CI build doesn't. Should the CI build be updated in someway to catch this kind of error? You're clearly building on Windows: is this required?

**Comment by MaggieYingYi** [comment]
> 
> 
> It would be useful to know why this build fails but the CI build doesn't.
>

The above build command is targeted on all targets. The CI build is only targeted on X86 by passing the `-DLLVM_TARGETS_TO_BUILD=X86`

> Should the CI build be updated in someway to catch this kind of error? 
>
I think we should.

> You're clearly building on Windows: is this required?
>
There is no special requirement, just build on all targets.

**Comment by paulhuggett** [comment]
>> Should the CI build be updated in someway to catch this kind of error?
> I think we should.

Will you do this as part of PR#100? (Bear in mind that we’re very close to the CI time limit, so this may not p=be possible unless another CI solution can be found.)

**Comment by MaggieYingYi** [comment]
> 
> 
> > > Should the CI build be updated in someway to catch this kind of error?
> > > I think we should.
> 
> Will you do this as part of PR#100? (Bear in mind that we’re very close to the CI time limit, so this may not be possible ATM.)

Good point. I prefer to do the CI change and PR#100 separately if we want to change CI build. For the CI time limit issue, Russ knew more but he is on holiday. Should I create a separate issue to check whether we could change CI build?

**Comment by paulhuggett** [comment]
> Should I create a separate issue to check whether we could change CI build?

No, I think this one should be enough.

**Comment by MaggieYingYi** [comment]
> 
> 
> > Should I create a separate issue to check whether we could change CI build?
> 
> No, I think this one should be enough.

Ok, Are you happy me to merge PR#100 back to master branch?

**Comment by paulhuggett** [comment]
> Are you happy me to merge PR#100 back to master branch?

Yes, absolutely.

**Comment by rgal** [comment]
> Will you do this as part of PR#100? (Bear in mind that we’re very close to the CI time limit, so this may not be possible ATM.)

Yes, I think that we are close to a number of limits on the github actions free machines, including disk space and memory. I'll create a task to add all targets when we move to something more substantial for CI.

**Comment by paulhuggett** [comment]
> Yes, I think that we are close to a number of limits on the github actions free machines, including disk space and memory. I'll create a task to add all targets when we move to something more substantial for CI.

With this in mind, we can probably close this bug.
